Project nemmy {
  database_type: 'PostgreSQL'
  Note: '''
    # nemmy Database
    **markdown content here**
  '''
}

Table users {
  id int [pk, increment]
  username varchar(255) [not null, unique]
  display_name varchar(255) [not null]
  profile_image_url varchar(255)
  created_at timestamp
  updated_at timestamp
  note: "ユーザーの情報を管理する"
}

Table subjects {
  id int [pk, increment]
  user_id int [note: 'user_idがnullの場合はサービス共通の科目を表す']
  name varchar(255) [not null]
  description text
  note: '勉強科目を管理する'
}

Table records {
  id int [pk, increment]
  subject_id int [not null]
  started_at timestamp [not null]
  duration int [not null, note: '単位は秒']
  comment text
  note: '勉強時間を管理する'
}

Ref: users.id < subjects.user_id
Ref: subjects.id < records.subject_id
